// <copyright file="EmpGrenadeConfig.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <auto-generated>

using System.Collections.Generic;
using System.ComponentModel;
using Exiled.CustomItems.API;
using Exiled.CustomItems.API.Features;
using Exiled.CustomItems.API.Spawn;

#pragma warning disable 1591

namespace CustomItems.ItemConfigs
{
    public class EmpGrenadeConfig
    {
        [Description("How long the EMP effect should last on the rooms affected.")]
        public float Duration { get; set; } = 20f;

        [Description("Where on the map items should spawn, and their % chance of spawning in each location.")]
        public SpawnProperties SpawnProperties { get; set; } = new SpawnProperties
        {
            Limit = 1,
            DynamicSpawnPoints = new List<DynamicSpawnPoint>
            {
                new DynamicSpawnPoint
                {
                    Chance = 100,
                    Location = SpawnLocation.Inside173Gate
                },
            },
            StaticSpawnPoints = new List<StaticSpawnPoint>
            {
                new StaticSpawnPoint
                {
                    Chance = 50,
                    Name = "somewhere",
                    Position = new Vector(100, 25, 40)
                }
            }
        };

        [Description("Whether or not the grenade should explode immediately when it collides with something.")]
        public bool ExplodeOnCollision { get; set; } = true;
        
        [Description("How long the fuse duration should be. Has no effect if ExplodeOnCollision is true.")]
        public float FuseDuration { get; set; } = 3f;

        [Description("The Custom Item ID for this item.")]
        public uint Id { get; set; } = 1;
        
        [Description("The description of this item show to players when they obtain it.")]
        public string Description { get; set; } = "This flashbang has been modified to emit a short-range EMP when it detonates. When detonated, any lights, doors, cameras and in the room, as well as all speakers in the facility, will be disabled for a short time.";

        [Description("The name of this item shown to players when they obtain it.")]
        public string Name { get; set; } = "EM-119";

        [Description("How many of this item are allowed to naturally spawn on the map when a round starts. 0 = unlimited")]
        public int SpawnLimit { get; set; } = 1;

        [Description("Whether or not EMP grenades will open doors that are currently locked.")]
        public bool OpenLockedDoors { get; set; } = true;

        [Description("Whether or not EMP grenades will open doors that require keycard permissions.")]
        public bool OpenKeycardDoors { get; set; } = true;
    }
}