// <copyright file="GrenadeLauncherConfig.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <auto-generated>

using System.Collections.Generic;
using System.ComponentModel;
using Exiled.CustomItems.API;

#pragma warning disable 1591

namespace CustomItems.ItemConfigs
{
    public class GrenadeLauncherConfig
    {
        [Description("Whether or not players will need actual frag grenades in their inventory to use as ammo. If false, the weapon's base ammo type is used instead.")]
        public bool UseGrenades { get; set; } = true;
        
        [Description("How many rounds a single reload should give. Note that weapons that fire more quickly than others will want lower clip sizes to prevent a nightmare of explosions. Unless that's your thing.. No judgement.")]
        public int ClipSize { get; set; } = 1;
        
        [Description("The type of weapon this one will be modeled after.")]
        public ItemType ItemType { get; set; } = ItemType.GunLogicer;

        [Description("Where on the map items should spawn, and their % chance of spawning in each location.")]
        public SpawnProperties SpawnProperties { get; set; } = new SpawnProperties
        {
            Limit = 1,
            DynamicSpawnLocations = new List<DynamicItemSpawn>
            {
                new DynamicItemSpawn
                {
                    Chance = 50,
                    Location = SpawnLocation.Inside049Armory
                },
                new DynamicItemSpawn
                {
                    Chance = 40,
                    Location = SpawnLocation.InsideHczArmory
                }
            }
        };
        
        [Description("The speed of grenades when they shoot out of the weapon.")]
        public float GrenadeSpeed { get; set; } = 1.5f;
        
        [Description("The max duration of the fuse of grenades shot from the weapon. Note, these grenades will always explode immediatly when they collide with something, but this can be used with slow-moving grenades to cause mid-air explosions.")]
        public float FuseTime { get; set; } = 1f;

        [Description("The Custom Item ID for this item.")]
        public int Id { get; set; } = 2;
        
        [Description("The description of this item show to players when they obtain it.")]
        public string Description { get; set; } = "This weapon will launch grenades in the direction you are firing, instead of bullets. Requires Frag Grenades in your inventory to reload.";

        [Description("The name of this item shown to players when they obtain it.")]
        public string Name { get; set; } = "GL-119";
        
        [Description("How many of this item are allowed to naturally spawn on the map when a round starts. 0 = unlimited")]
        public int SpawnLimit { get; set; } = 1;
    }
}