// <copyright file="Scp1499Config.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <auto-generated>

using System.Collections.Generic;
using System.ComponentModel;
using Exiled.CustomItems.API;

#pragma warning disable 1591

namespace CustomItems.ItemConfigs
{
    public class Scp1499Config
    {
        [Description("How long the SCP-1499 can be wore, before automaticly player takes it off. (set to 0 for no limit)")]
        public float Duration { get; set; } = 15f;
        
        [Description("Where on the map items should spawn, and their % chance of spawning in each location.")]
        public SpawnProperties SpawnProperties { get; set; } = new SpawnProperties(
            new List<CustomItemSpawn>
            {
                new DynamicSpawn(SpawnLocation.InsideHid, 10),
            }, 1);

        [Description("The Custom Item ID for this item.")]
        public int Id { get; set; } = 12;

        [Description("The description of this item show to players when they obtain it.")]
        public string Description { get; set; } = "The gas mask that temporarily teleports you to another dimension, when you put it on.";

        [Description("The name of this item shown to players when they obtain it.")]
        public string Name { get; set; } = "SCP-1499";

        [Description("How many of this item are allowed to naturally spawn on the map when a round starts. 0 = unlimited")]
        public int SpawnLimit { get; set; } = 1;
    }
}
