// <copyright file="SniperRifleConfig.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>
// <auto-generated>

using System.Collections.Generic;
using System.ComponentModel;
using Exiled.CustomItems.API;
using Exiled.CustomItems.API.Spawn;

#pragma warning disable 1591

namespace CustomItems.ItemConfigs
{
    public class SniperRifleConfig
    {
        [Description("The amoutn of extra damage this weapon does, as a multiplier.")]
        public float DamageMultiplier { get; set; } = 7.5f;
        
        [Description("How many rounds are usable after a single reload.")]
        public uint ClipSize { get; set; } = 1;
        
        [Description("The base weapon this one is modeled after.")]
        public ItemType ItemType { get; set; } = ItemType.GunE11SR;
        
        [Description("Where on the map items should spawn, and their % chance of spawning in each location.")]
        public SpawnProperties SpawnProperties { get; set; } = new SpawnProperties
        {
            Limit = 1,
            DynamicSpawnPoints = new List<DynamicSpawnPoint>
            {
                new DynamicSpawnPoint
                {
                    Chance = 100,
                    Location = SpawnLocation.InsideHid
                },
                new DynamicSpawnPoint
                {
                    Chance = 40,
                    Location = SpawnLocation.InsideHczArmory
                }
            }
        };

        [Description("The Custom Item ID for this item.")]
        public uint Id { get; set; } = 9;
        
        [Description("The description of this item show to players when they obtain it.")]
        public string Description { get; set; } = "This modified E-11 Rifle fires high-velocity anti-personnel sniper rounds.";

        [Description("The name of this item shown to players when they obtain it.")]
        public string Name { get; set; } = "SR-119";
        
        [Description("How many of this item are allowed to naturally spawn on the map when a round starts. 0 = unlimited")]
        public int SpawnLimit { get; set; } = 1;
    }
}